# FirstJoinPlus v1.8 Configuration -- Please see https://github.com/chaseoes/FirstJoinPlus/wiki/Configuration #
settings:
  first-join-message: '&d%player-name has joined the game for the first time (%unique-players total players have joined)!'
  teleport-delay: 0
  notify-sound: LEVEL_UP
  update-checking: true
  debug: false
on-first-join:
  show-first-join-message: true
  teleport: false
  show-smoke: true
  play-notify-sound: true
  launch-firework: false
  give-xp: 5
  set-invincible: 0
  give-items:
    enabled: true
    items:
    - WOOD_PICKAXE
    - BREAD:5
    - WOOL:10:6
  give-written-books:
    enabled: false
    book-files:
    - rules.txt
  send-motd:
    enabled: false
    messages:
    - '&2Welcome to our server, %player-name! Customize this message in the FirstJoinPlus configuration:'
    - '&6http://dev.bukkit.org/server-mods/firstjoinplus/'
  run-commands:
    enabled: false
    commands-to-run:
    - me just joined for the first time!
  run-console-commands:
    enabled: false
    commands-to-run:
    - promote %player-name