## FirstJoinPlus v1.5 Configuration -- Please see https://github.com/chaseoes/FirstJoinPlus/wiki/Configuration ##
settings:
    onlyfirstjoin: false
    worldname: world
    updatecheck: true
    metrics: true
    itemonfirstjoin: false
    firstjoinspawning: false
    showfirstjoinmessage: true
    showfirstjoinmotd: true
    showfirstjoinsmoke: true
    numberonfirstjoin: true
    commandsonfirstjoin: false
    console-commandsonfirstjoin: false
    xponfirstjoin: 0
    numberonjoin: false
messages:
    firstjoinmessage: '&d%name% has joined the game for the first time!'
    joinmessage: '&e%name% has joined the game.'
    leavemessage: '&e%name% has left the game.'
    kickmessage: '%none%'
    numbermessage: '&d%number% unique players have joined the server!'
items:
   - 57.32.0
motd:
    - '&bWelcome to our server, &6%name%&b!'
    - '&bThis message can be customized in the &6FirstJoinPlus &bconfig!'
    - '&bWebsite! http://dev.bukkit.org/server-mods/firstjoinplus/'
commands:
    - 'me just joined for the first time!'
console-commands:
    - 'say %player% just joined for the first time!'
spawn:
    x: 1
    y: 1
    z: 1
    pitch: 1
    yaw: 1
    world: world