## FirstJoinPlus v1.4 Configuration -- Please see https://github.com/chaseoes/FirstJoinPlus/wiki/Configuration ##
settings:
    onlyfirstjoin: false
    worldname: world
    debug: false
    updatecheck: true
    itemonfirstjoin: false
    firstjoinspawning: false
    showfirstjoinmessage: true
    showfirstjoinmotd: true
    showfirstjoinsmoke: true
    numberonfirstjoin: false
    commandsonfirstjoin: false
    showjoinmessage: true
    showleavemessage: true
    showkickmessage: true
messages:
    firstjoinmessage: "&d%name% has joined the game for the first time!"
    joinmessage: "&e%name% has joined the game."
    leavemessage: "&e%name% has left the game."
    kickmessage: "&e%name% was kicked from the game!"
    numbermessage: "&d%number% unique players have joined the server!"
items:
   - 57.32.0
motd:
    - '&bWelcome to our server, &6%name%&b!'
    - '&4This message can be customized in the FirstJoinPlus config!'
commands:
    - 'me just joined for the first time!'
spawn:
    x: 1
    y: 1
    z: 1
    pitch: 1
    yaw: 1