## FirstJoin Config File ##
settings:
    worldname: world
    numberonjoin: true
messages:
    firstjoinmessage: "&d%name% has joined the game for the first time!"
    joinmessage: "&e%name% has joined the game."
    leavemessage: "&e%name% has left the game."
    kickmessage: "&e%name% was kicked from the game!"
    numbermessage: "&d%number% unique players have joined the server!"