name: FirstJoinPlus
main: me.chaseoes.firstjoinplus.FirstJoinPlus
version: 1.2.1
dev-url: http://dev.bukkit.org/server-mods/firstjoinplus/
description: Controls all aspects of when players join for the first time.
author: chaseoes
website: http://dev.bukkit.org/server-mods/firstjoinplus/
commands:
  firstjoinplus:
    description: The main command for FirstJoinPlus.
    aliases: fjp
    usage: /firstjoinplus <reload|spawn|setspawn|motd>