name: ${project.name}
main: ${project.groupId}.${upload.dbo.slug}.${project.name}
version: ${project.version}
description: ${project.description}
author: chaseoes
dev-url: http://dev.bukkit.org/server-mods/${upload.dbo.slug}/
website: http://dev.bukkit.org/server-mods/${upload.dbo.slug}/
softdepend: [GeoIPTools]
commands:
  ${upload.dbo.slug}:
    description: ${project.name} command(s).
    aliases: fjp
    usage: /${upload.dbo.slug} [reload|setspawn|debug]
permissions:
  ${upload.dbo.slug}.reload:
    description: Permission to use the /${upload.dbo.slug} reload command.
  ${upload.dbo.slug}.setspawn:
    description: Permission to use the /${upload.dbo.slug} setspawn command.
  ${upload.dbo.slug}.debug:
    description: Permission to use the /${upload.dbo.slug} debug command.