name: ${plugin.name}
main: ${plugin.groupID}.${plugin.name.lower}.${plugin.name}
version: ${plugin.version}
api-version: 1.13
description: ${project.description}
author: chaseoes
dev-url: http://dev.bukkit.org/server-mods/${plugin.name.lower}/
website: http://dev.bukkit.org/server-mods/${plugin.name.lower}/
softdepend: [GeoIPTools]
commands:
  ${plugin.name.lower}:
    description: ${plugin.name} command(s).
    aliases: fjp
    usage: /${plugin.name.lower} [reload|setspawn|debug]
permissions:
  ${plugin.name.lower}.reload:
    description: Permission to use the /${plugin.name.lower} reload command.
  ${plugin.name.lower}.setspawn:
    description: Permission to use the /${plugin.name.lower} setspawn command.
  ${plugin.name.lower}.debug:
    description: Permission to use the /${plugin.name.lower} debug command.
